apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: card-web
  description: The place to be, for great card players
  labels:
    example.com/custom: card_label_value
  annotations:
    example.com/service-discovery: cardplayersweb
    circleci.com/project-slug: github/example-org/cardplayers-website
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: public-websites
